version: "3.8"

services:
  app:
    build: .
    container_name: dcs-back
    ports:
      - "${PORT:-9099}:9099"
    environment:
      - PORT=9099
      - UPLOAD_DIR=/app/uploads
      - URL_PUBLIC=${URL_PUBLIC}
      - CORS_ALLOW_ORIGINS=*
    volumes:
      - uploads:/app/uploads

volumes:
  uploads:
