version: "3.8"

services:
  app:
    build: .
    container_name: ${CONTAINER_NAME:-dcs-back-v0}
    ports:
      - "${PORT:-9099}:9099"
    environment:
      - PORT=${PORT}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - URL_PUBLIC=${URL_PUBLIC}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
      - SUPER_ADMIN_USERNAME=${SUPER_ADMIN_USERNAME}
    volumes:
      - uploads:/app/uploads

volumes:
  uploads:
