
@BASE_URL = https://back.road2theoscars.tech
# @BASE_URL = http://localhost:9099


### TESTEAR GENERACION DE VIDEOS CON SINCRONIZACION DE GALERIA
POST {{BASE_URL}}/api/v1/studio/video/generate
Content-Type: application/json

{
    "model": "dreamina-seedance-2-0-gallery",
    "content": [
        {
            "type": "text",
            "text": "la mujer  [Image1] cuando ve un perro callejero se asusta"
        },
        {
            "type": "image",
            "id": "8b0352bb-2c71-4b48-8d7b-6996e0292265",
            "name": "44.jpg",
            "text": "Sofia"
        }
    ],
    "ratio": "16:9",
    "duration": 5,
    "camerafixed": false,
    "seed": "",
    "quality": "standard",
    "quantity": 1,
    "watermark": false,
    "resolution": "480p",
    "generate_audio": false,
    "image_mode": "PIL",
    "project_id": "388083eb-3b0c-4321-af47-24bf112086d0",
    "scene_id": "956729b0-3aa1-4e22-ac56-7e8f66b1f56e",
    "scene_code": "SC02",
    "take_number": 1,
    "user_id": 2
}